[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "readthedocs-eniocc"
authors = [{name = "Ênio Rodrigues", email = "eniocc@gmail.com"}]
dynamic = ["version", "description"]
